### ISSUE TITLE
Update version of cake this uses

### ISSUE THREAD

**Issue by TraGicCode** [Philo/cake-webpack#12] opened 2018-12-20 23:34 UTC
Hey,

I was trying to use this in my cake script and getting an error saying this addin is referencing an old version of cake and therefore cannot be used.

**Comment by gep13** [comment] 2019-09-01 19:55
@TraGicCode this is really a duplicate of this issue:  https://github.com/cake-contrib/Cake.Webpack/issues/9

Going to close this one out.  Thanks for raising it though.

**Closed as completed by gep13** 2019-09-01 19:55 UTC
